name: Release notification

on:
  release:
    types: [published, released]

jobs:
  send-slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send slack message
        run: |
          echo "Github release ref: ${{ github.ref_name }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Event type: ${{ github.event.type }}"
