name: Release notification logger

on:
  release:
    types: [released]

jobs:
  send-slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send slack message
        run: echo "Release URL ${{ github.server_url }}/${{ github.repository }}/releases/tag/${{ github.ref_name }}"
