name: Release notification

on:
  release:
    types: [published, released]

jobs:
  send-slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: Send slack message
        run: echo "Github released published or released"
